### ISSUE TITLE
OpenBLAS detection on Windows (and Linux) wanted

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#144]
Hi,

currently, the CMake's FindBLAS package  does not detect the OpenBLAS library, which is the only one working for MS Windows:

https://ci.appveyor.com/project/bast/autocmake/build/1.0.413#L298

The previous *math_libs.cmake* contained working OpenBLAS detection. Would it be possible to have the corresponding *openblas.cmake* macro  ?

Also, we would need Linux CI service testing openblas library detection. 

Is there a some flag for math-libs preference (like pick openblas instead of system_native blas or atlas blas) ? Is it possible to combine libraries (like --openblas --blas ) in case of missing routines ?

**Comment by bast** [comment]
It is certainly possible and certainly the plan to have such a module.
I don't understand the question with the preference since you
then tell exactly what you want by the flags. And combining math libraries
is tricky. From the Autocmake perspective this is no problem but the code
has to then deal with multiple definitions.

**Comment by miroi** [comment]
Hi,

wrt combining libraries: for example, openblas does not contain the whole lapack. Therefore I would combine *-openblas -lapack* to supply missing lapack routines in openblas. Is it goog approach ?

Also, how about the automatic detection of MKL (ESSL)  libraries ?

**Comment by bast** [comment]
I have created a forum to discuss things and will try to keep issues for real issues.
Please see http://autocmake.readthedocs.org/en/latest/general/help.html
