### ISSUE TITLE
Can  I implement a new test, fc_lapack ?

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#47]
In order to test linking of the lapack library, hereby I am asking for permission to write simple test of linking the lapack library with Fortran program.

**Comment by bast** [comment]
You don't need to ask for any permissions. You can do everything that the license allows.
Just do it. Everything that is of general interest and brings the code forward will be integrated.

**Comment by miroi** [comment]
Fine; but first before doing something and asking for pull  request, I ask if the proposed feature is wanted.

I would expect some guidance, like "yes, we need to test lapack lib detection also, please implement this".

**Comment by bast** [comment]
So far we are a small community and there are no hard and fast rules but hopefully
the community will grow.
My personal recommendation/workflow is this:
- If you need it, just do it and don't ask.
- If you don't need it, don't do it.
- If it is good for other people, other people will want it and merge it or fork from you.
- If it is good for everybody, it will be incorporated.
- If I need it, I just do it.
- If I need it but don't have the time and risk to forget, I open an issue for it so that I don't forget and/or somebody else implements it.
Think decentral. Not every feature has to be available in the central repo immediately. Let the features
fight it out. Survival of the fittest.

**Comment by miroi** [comment]
Fine; these recommendations for developers should be made part of the developer documentation, together with TODO/WISH list.
