### ISSUE TITLE
Better comprehensive testing script...

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#56]
Hi,
I opening issue concerning the need of more flexible testing script.  

i) For all tests, I would need option for selecting compiler(s), math library, integer-mode, linking options (static vs dynamic).

ii) The test script should be able to pick up selected tests only.

iii) Also it would be good to have ctest/CDash option to display results of tests. The CI services are good, though the provide only GNU software. Contrary many machines we are operating have commercial compilers/libraries available.

Even the PR into autocmake should be checked against CDash web results employing commercial compilers/math libraries. Who knows is some good intented change into math_libs.cmake does not hurt my favourite  **pgf90+MKL-static** tests ?

**Comment by bast** [comment]
I think I understand your concerns but my concern is that we are trying to create a new CMake here
and get full control over all compilers, libraries, versions, and at least for me this is not Autocmake's ambition.

I have initially added tests so that I notice when I break something very basic. I don't want to test all the various compilers because that is impossible for me. Autocmake is not an isolated project.
We use it in various codes ourselves and test the modules also in those codes. If we break something that is difficult to test, we will notice either ourselves or the users will tell us via issues.
Typically we notice very quickly if we break something for ourselves.

Why would we want to test only selected tests and not all tests?
And why do we want to test commercial compilers or libraries? The bulk of Autocmake
is hopefully portable CMake code. AFAICS it is only in the linking where different compilers
and architectures enter. This is a difficult problem that we cannot completely solve IMO.

I think what we need to do now is to isolate the parts which are compiler/vendor-dependent
from the parts which are portable. We need to modularize. My hope is that the portable part will
make 95% of the code or more. Hopefully the right testing will crystallize
over time but I don't think we will benefit from trying to make the testing comprehensive
at the sacrifice of simplicity and clarity.

**Comment by bast** [comment]
One thing I can do is to create space for this project on https://testboard.org
for field studies but for me personally the "official" testing is on Travis and Appveyor
until we realize that this is not enough.

**Comment by bast** [comment]
I am closing this issue. If you want to continue a discussion on any of the above points please
open an issue just for that point. Specific issues are better than general multi-issue issues which
are difficult to track.
