### ISSUE TITLE
Missing working ctest example

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#72]
As I am trying to adapt tests for https://github.com/miroi/mathlibs-tester, I am missing working ctest-autocmake example.

Is it worth for consideration ?

**Comment by bast** [comment]
I don't understand - what exactly is missing and where?

**Comment by miroi** [comment]
autocmake lacks very ctest example, IMHO (and I can not set up it in another project as related issue...)

**Comment by bast** [comment]
OK testing is very project-dependent. We could abstract one or two lines
```
include(CTest)
enable_testing()
```
but still the user has to write something. One thing that Autocmake cannot do much
about is help with targets since they are different for every project. But we can
help with everything else.

I think what you are missing is documentation on how to do this.
I will add some doc although it falls a bit into the first two FAQs here:
http://autocmake.readthedocs.org/en/latest/developers/faq.html#faq-for-developers

**Comment by miroi** [comment]
Well, I'd need one very simple running Ctest in autocmake. I can't set it up in another projekt, based on autocmake.

**Comment by bast** [comment]
Here are explicit examples where I use that:
https://github.com/bast/xcint/blob/master/cmake/custom/test.cmake
https://github.com/bast/numgrid/blob/master/cmake/custom/test.cmake

**Comment by miroi** [comment]
In this example a new test requires own  target and libraries.
But in Autocmake we already have **add_executable(example example.F90)**. 

Plain **add_test(${PROJECT_BINARY_DIR}/bin/example)**  is not working.

**Comment by miroi** [comment]
Well, maybe I should try the *cmake/custom/test.cmake* approach.

**Comment by bast** [comment]
The `add_test` can test in principle any binary or script or command. It does not need to be a target. It creates a "make test" target.

**Comment by miroi** [comment]
I got the make test target. Even make test works after the target compilation. But the configuration is not working, claiming missing libraries, LAPACK/BLAS libraries not found for the project! .

**Comment by miroi** [comment]
Well, *make VERBOSE=1 ExperimentalConfigure* give error of LAPACK_FOUND=FALSE. Strange that when calling it as test, is does not find libraries, althogh the previous compilation works....
